services:
  dynamodb-test:
    image: amazon/dynamodb-local:latest
    container_name: actingweb-test-dynamodb
    command: '-jar DynamoDBLocal.jar -sharedDb -dbPath ./data'
    ports:
      - '8001:8000'
    volumes:
      - ./tests/integration/dynamodb-data:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
    networks:
      - test-network

networks:
  test-network:
    driver: bridge
